#!/bin/bash
#sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub org.linux_hardware.hw-probe
flatpak install -y flathub io.missioncenter.MissionCenter
##flatpak install -y flathub io.github.arunsivaramanneo.GPUViewer
##flatpak install -y flathub org.virt_manager.virt-manager
##flatpak install -y flathub org.mozilla.Thunderbird
flatpak install -y flathub io.github.amit9838.mousam
flatpak install -y flathub io.gitlab.adhami3310.Converter
flatpak install -y flathub io.gitlab.news_flash.NewsFlash
flatpak install -y flathub com.rafaelmardojai.Blanket
flatpak install -y flathub io.github.nokse22.inspector
flatpak install -y flathub org.nickvision.tubeconverter
flatpak install -y flathub de.haeckerfelix.Shortwave
flatpak install -y flathub com.github.tenderowl.frog
flatpak install -y flathub io.github.chidiwilliams.Buzz
flatpak install -y flathub io.github.mrvladus.List
flatpak install -y flathub io.github.alainm23.planify
flatpak install -y flathub net.nokyan.Resources
flatpak install -y flathub me.iepure.devtoolbox
flatpak install -y flathub de.schmidhuberj.tubefeeder
flatpak install -y flathub org.kde.klevernotes
flatpak install -y flathub org.videolan.VLC
flatpak install -y flathub io.bassi.Amberol
##flatpak install -y flathub org.libreoffice.LibreOffice
flatpak install -y flathub org.audacityteam.Audacity
flatpak install -y flathub org.gimp.GIMP
flatpak install -y flathub org.kde.krita
flatpak install -y flathub org.keepassxc.KeePassXC
flatpak install -y flathub org.gnome.Aisleriot
##flatpak install -y flathub org.chromium.Chromium
flatpak install -y flathub org.localsend.localsend_app
##flatpak install -y flathub com.freerdp.FreeRDP   # doesnt work on Wayland?
##flatpak install -y flathub com.rustdesk.RustDesk # doesnt work on Wayland?
## flatpak install -y flathub com.anydesk.Anydesk  # doesnt work on Wayland?

## list
##flatpak list --columns=ref,size

## list sorted by size
## flatpak list --app --columns=size,name | sort -h

## uninstall
## flatpak uninstall org.gnome.VirtualMachineManager

## remove all data associated with the app, add the --delete-data flag:
## flatpak uninstall --delete-data org.gnome.VirtualMachineManager

flatpak install -y flathub io.github.cboxdoerfer.FSearch

flatpak install -y flathub org.localsend.localsend_app
flatpak install -y flathub net.veloren.airshipper
flatpak install -y flathub de.haeckerfelix.Shortwave
flatpak install -y flathub io.missioncenter.MissionCenter
flatpak install -y flathub de.schmidhuberj.tubefeeder
flatpak install -y flathub io.github.alainm23.planify
flatpak install -y flathub org.kde.klevernotes
flatpak install -y flathub io.github.flattool.Warehouse
flatpak install -y flathub io.github.mrvladus.List
flatpak install -y flathub org.freedesktop.dabrain34.GstPipelineStudio
flatpak install -y flathub net.nokyan.Resources
flatpak install -y flathub it.mijorus.gearlever
flatpak install -y flathub me.iepure.devtoolbox
flatpak install -y flathub com.chroniclogic.Zatikon
#flatpak install -y flathub net.mkiol.SpeechNote
flatpak install -y flathub com.github.tchx84.Flatseal
flatpak install -y flathub io.github.cboxdoerfer.FSearch
flatpak install -y flathub com.poweriso.PowerISO
flatpak install -y flathub io.github.dosbox-staging

